### ISSUE TITLE
Model implementation: why upsample ?

### ISSUE THREAD

**Issue by vfdev-5** [katsura-jp/efficientnet-pytorch#6]
@katsura-jp I'm wondering why there is upsample operation in before stem ?

https://github.com/katsura-jp/efficientnet-pytorch/blob/d9c5abddb4ecbe1ee4e15940c357d9c4c385e9f5/model/efficientnet.py#L153-L156

**Comment by katsura-jp** [comment]
@vfdev-5
EfficientNet linearly increases the resolution for each version (B0,B1,B2,...,B7).
For example, ImageNet input image resolution is 224x224 commonly, and input resolution of EfficientNet-B0 is 224x224(scale ratio: 1) and EfficientNet-B7 resolution is 600x600(scale ratio: 600/224).
The original tensorflow implementation is upsampled outside the model but not in the model, but I include it in the forward module for readability of the model.
